### ISSUE TITLE
Look into different options (i.e ESRI Story Map)

### ISSUE THREAD

**Issue by cahhansen** [spence97/NWM_Retro_Analysis#11]

**Comment by jshafiei** [comment]
I found this one very interesting:
https://www.arcgis.com/apps/Cascade/index.html?appid=b0b60109b23541c99014bf5f8508605e

**Comment by cahhansen** [comment]
Web development approaches (including leaflet applications) don't fit well with anyone's interests. Leaflet could be used inside of an R Shiny Application if an interactive experience is a priority, but it does not seem to be.
ESRI Story Maps seem to be the best option and fits well with our project.
